<center><img src="/work/img/numpy_logo.png"></center>

<h1>NumPy (Numerical Python)</h1>
<p><em><b>Manual de Referencia NumPy:</b> <a href="https://numpy.org/doc/stable/">https://numpy.org/doc/stable/</a></em></p>
<p>Es una librería de Python que provee una serie de métodos para realizar operaciones matemáticas sobre una estructura de datos en forma de matriz (llamado <b>array</b>), que puede ser uni-dimensional (arreglo), bi-dimensional (matriz) o n-dimensional (tensores).</p>
<center><img src="/work/img/numpy1.png"></center>
<p>Un array NumPy es un paquete de matrices N-dimensional que tienen forma de filas y columnas, en la que tenemos varios elementos que están almacenados en sus respectivas ubicaciones de memoria.</p>


<h3>Instalación</h3>
<p>Al trabajar en un entorno local, debemos instalar el paquete NumPy. <b>Recordá crear un entorno virtual previamente.</b> Si estamos trabajando en entornos tipo notebook, no necesitamos instalar ningún paquete para trabajo con datos (NumPy, PanDas, Matplotlib, etc.), sólo necesitamos importarlos.</p>
<center><img src="/work/img/instala_numpy.png"></center>

<h3>Importando la librería</h3>
<center><img src="/work/img/importar_numpy.png"></center>

In [ ]:
import numpy as np
from scipy import stats

#USOS BÁSICOS
lista_nros = [12,12,14,15,16,16,16,20,2,3,4,5,5,7,8,10,22,22]

'''
Para poder manipular mi lista python con numpy, necesito convertirla en un ARREGLO o
VECTOR
Voy a usar el método array() de numpy y le voy a pasar como parámetro la lista
Como le puse un alias a mi numpy importado (np), lo voy a usar para invocar a
este método de ahora en adelante
'''
array_nros = np.array(lista_nros)
# array_nros = np.array([12,12,14,15,16,16,16,20,2,3,4,5,5,7,8,10,22,22]) # -> otra opción

print(lista_nros)
print(type(lista_nros))
print()
print(array_nros) # misma distribución que la lista, pero en lugar de comas, los elementos están separados por dos espacios
print(type(array_nros)) # devuelve un dato de tipo numpy.ndarray


#numpy -> es un objeto que generó numpy
#array -> es un arreglo o vector
#n: numeric
#d: dimension

[12, 12, 14, 15, 16, 16, 16, 20, 2, 3, 4, 5, 5, 7, 8, 10, 22, 22]
<class 'list'>

[12 12 14 15 16 16 16 20  2  3  4  5  5  7  8 10 22 22]
<class 'numpy.ndarray'>


<h3>Medidas de tendencia central en NumPy</h3>

In [ ]:
# MEDIA
array_nros = np.array([5,5,5,7,8,10,12,12,14,15,16,16,16,20,2,2,2,3,4,22,22])
media = np.mean(array_nros)
media2 = array_nros.mean()
#print(media1,media2)
print("Promedio/Media:", f"{media:.2f}") # Numpy me da hasta 16 decimales si no se especifica otra cosa


Promedio/Media: 10.38


In [ ]:
# MEDIANA -> método  median()
mediana = np.median(array_nros)
# mediana = array_nros.median() # No funciona
print("Mediana es:" , mediana)


Mediana es: 10.0


In [ ]:
# CUARTILES
q1 = np.quantile(array_nros, 0.25)
q2 = mediana
q3 = np.quantile(array_nros, 0.75)
print(f"Q1 = {q1}, Q2 = {q2}, Q3 = {q3}")

Q1 = 5.0, Q2 = 10.0, Q3 = 16.0


In [ ]:
# PERCENTIL -> Es una medida de dispersión parecida a los cuartiles pero que divide
# la muestra en 100 => trabaja con porcentajes
# método percentile(arreglo, cuántos elementos tomar)
p60 = np.percentile(array_nros, 60)
p20 = np.percentile(array_nros, 20)
p50 = np.percentile(array_nros, 50)
print("Percentil 60:", p60) # el 60% de los datos -> menor a q3, el 75%
print("Percentil 20:", p20) # el 20% de los datos -> menor a q1, que representa el 25%
print("Percentil 50:", p50) # lógicamente coincide con q2 = la mediana

Percentil 60: 12.0
Percentil 20: 4.0
Percentil 50: 10.0


In [ ]:
''' MODA
me devuelve un objeto de tipo ModeResult(array_con_el_primer_valor_que_encuentra,
recuento_de_apariciones)
Sólo devuelve la primera ocurrencia en un vector ORDENADO si hay más valores,
los ignora '''

moda = stats.mode(array_nros)
print("Moda:", moda)

# son todos módulos de numpy, excepto mode()


Moda: ModeResult(mode=array([2]), count=array([3]))


In [ ]:
# Varianza -> método var()
varianza = np.var(array_nros)
print("Varianza:", varianza)
print("Varianza:", f"{varianza:.2f}") # formateado a dos decimales con :.2f


Varianza: 43.188208616780045
Varianza: 43.19


In [ ]:
# Desvío Standard -> método std()
desvio_st = np.std(array_nros)
print("Desvío Standard:", desvio_st)

# Acá puedo confirmar que si hago desvio_st**2, obtengo la varianza -> repaso de conceptos
print('Varianza calculada:',desvio_st ** 2)

Desvío Standard: 6.571773627931812
Varianza calculada: 43.188208616780045


<h3>Creando estructuras de datos con NumPy</h3>

Los arreglos en Numpy tienen que tener <b>sí o sí</b> los mismos tipos de datos -> los diferencia de las listas Py.

A los elementos de un vector se accede como a lo de los iterables conocidos -> con índice.

Les puedo aplicar slicing.

In [ ]:
# CREAR ARREGLOS = ARRAY = VECTOR -> 1 fila, n columnas
# MATRIZ UNIDIMENSIONAL

lista_numeros = [1,10,100,3,75,36,79,11]
arr = np.array(lista_numeros)
print(arr)
print(type(arr))
print()
print("Primer elemento:",arr[0])
print("Último elemento:",arr[-1])
print()
print('Tamaño del arreglo:',len(arr))

[  1  10 100   3  75  36  79  11]
<class 'numpy.ndarray'>

Primer elemento: 1
Último elemento: 11

Tamaño del arreglo: 8


In [ ]:
# CREAMOS UNA MATRIZ = ARREGLO BI-DIMENSIONAL
lista_numeros = [[1,10,3],[9, 9, 11]]
print("LISTA Py")
print(lista_numeros)
print()
arr_numeros = np.array(lista_numeros)
print("ARREGLO NumPy")
print(arr_numeros)
print(type(arr_numeros))
print()
# Accediendo a los valores en una matriz -> x coordenadas [fila, columna]
print(arr_numeros[0,1])
print(arr_numeros[1,2])
print()

# ¿qué va pasar acá? recordando que en un vector los datos deben ser homogéneos
# me convierte todos los datos al tipo que sea menos limitante -> string
lv = [1, "hora", 0.5]
arr_lv = np.array(lv)
print(arr_lv)

LISTA Py
[[1, 10, 3], [9, 9, 11]]

ARREGLO NumPy
[[ 1 10  3]
 [ 9  9 11]]
<class 'numpy.ndarray'>

10
11

['1' 'hora' '0.5']


#### ACTIVIDAD
- Crear dos listas con datos de tipo homogéneo.
- Una de las listas -> convertirla a vector
- La otra -> convertirla a una matriz de 3 filas x 4 columnas

In [ ]:
l1 = [100, 200, 300]
a1 = np.array(l1)
print(a1,'\n')

l2 = [[11,12,13,14],[21,22,23,24],[31,32,33,34]]
a2 = np.array(l2)
print(a2,'\n')

[100 200 300] 

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]] 



### Forzando el tipo de dato

In [ ]:
array1 = np.array([[1.5,2,3,4],[5,6,7,8]])
print(array1)
print()

array2 = np.array([[1.5,2,3,4],[5,6,7,8]],dtype=np.int64)
print(array2)
print()
array3 = np.array([[11,12,13],[21,22,23]], dtype=np.float64)
print(array3)
print()

array4 = np.array([[11,12,13],[21,22,23]], dtype=np.str0)
print(array4)

[[1.5 2.  3.  4. ]
 [5.  6.  7.  8. ]]

[[1 2 3 4]
 [5 6 7 8]]

[[11. 12. 13.]
 [21. 22. 23.]]

[['11' '12' '13']
 ['21' '22' '23']]


### Arreglos vacíos
<p>A veces se crean arreglos vacíos, para luego ser rellenados.</p>
<p>Se inicializan con unos, ceros, valores espaciados uniformemente, valores constantes o valores aleatorios. </p>

In [ ]:
# arreglo de unos -> MÉTODO ONES  --> punto flotante
unos = np.ones(3)
print(unos)
print()

unos2 = np.ones((3, 5)) # doble paréntesis
print(unos2)
print()

unos3 = np.ones((3,5),dtype=np.int64) #convierto a entero
print(unos3)

[1. 1. 1.]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [ ]:
# arreglo de ceros

ceros1 = np.zeros(3)
print(ceros1)
print()

ceros2 = np.zeros((3,5))
print(ceros2)
print()

ceros3 = np.zeros((3,5),dtype=np.int64)
print(ceros3)
print()

[0. 0. 0.]

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]



In [ ]:
# llena todo el arreglo con el mismo valor
ochos = np.full((2,3),8)
print(ochos)

[[8 8 8]
 [8 8 8]]


In [ ]:
# arreglo de nros aleatorios -> MÉTODO RANDOM, submétodo, nros aleatorios entre 0 y 1
nros1 = np.random.random(3)
print(nros1)
print()

nros2 = np.random.random((3,5))
print(nros2)
print()

nros3 = np.random.randint(1,6,5)
print(nros3)
print()

nros4 = np.random.randint(1,6,(5,5))
print(nros4)
print()

[0.03699531 0.59913004 0.66488406]

[[0.28164602 0.60890533 0.84653474 0.47908729 0.7058582 ]
 [0.03442466 0.50908242 0.87055388 0.19040637 0.1435332 ]
 [0.21626411 0.82495661 0.93376959 0.32197314 0.84319347]]

[3 5 3 1 1]

[[3 3 2 5 4]
 [2 4 1 1 2]
 [3 5 4 5 3]
 [5 2 2 1 1]
 [3 4 1 2 2]]



Para crear arreglos con valores espaciados uniformemente podemos utilizar np.arange() y np.linspace()


In [ ]:
# np.arange(): deseo crear un arreglo con los valores comprendidos entre 0 y 100 a paso 5
esp5 = np.arange(0,101,5)
print(esp5)
print()

# np.linspace(): deseo crear 5 valores que se encuentren entre 0 y 2
esp6 = np.linspace(0,2,5)
# np.linspace(min, max, n) me divide el rango en min-max en n partes y llena el arreglo con los valores que me da la división
esp6 = np.linspace(0,2,5)
print(esp6)
print()


[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100]

[0.  0.5 1.  1.5 2. ]



<h3>Matriz identidad</h3>

In [ ]:
matriz_identidad = np.eye(4)
print(matriz_identidad)
print()

mt = np.identity(4, dtype=np.int64)
print(mt)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


<h3>Inspeccionar arreglos</h3>


In [ ]:
arreglo = np.array([(1, 3, 5, 7), (9.5, 3, 4, 5), (1, 1, 1, 1)])

print(arreglo)
print(arreglo.shape) # me da el formato fila-columna en una tupla -> (3,4)
print(arreglo.dtype) # devuelve el tipo de dato 
print(arreglo.size) # devuelve la cantidad de datos
print(len(arreglo)) # NO CONFUNDIR CON SIZE
print()
print("Tamaño calculado:",arreglo.shape[0] * arreglo.shape[1] )


[[1.  3.  5.  7. ]
 [9.5 3.  4.  5. ]
 [1.  1.  1.  1. ]]
(3, 4)
float64
12
3

Tamaño calculado: 12


<h3>Cambio de tamaño y forma</h3>

In [ ]:
#Para que sea posible, ambas matrices deben tener el mismo SIZE
matriz1 = np.array([(8, 9, 10), (11, 12, 13)])
print(matriz1)
print()

matriz2 = matriz1.reshape(3,2)
print(matriz2)
print()

matriz3 = matriz1.reshape(6,1)
print(matriz3)
print()

matriz4 = matriz1.reshape(1,6)
print(matriz4)
print()

matriz5 = matriz1.reshape(6)
print(matriz5)
print()

[[ 8  9 10]
 [11 12 13]]

[[ 8  9]
 [10 11]
 [12 13]]

[[ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]]

[[ 8  9 10 11 12 13]]

[ 8  9 10 11 12 13]



<h3>Operaciones matemáticas</h3>

In [ ]:
a = np.arange(4)
print(a)
print(a + 5)
print(a * 2)
print(a)

[0 1 2 3]
[5 6 7 8]
[0 2 4 6]
[0 1 2 3]


<h3>Universal functions (ufunc)</h3>
https://www.w3schools.com/python/numpy/numpy_ufunc.asp También ejecutan una operación elemento a elemento sobre un arreglo Reemplazan los operadores individuales. Son funciones nativas

Ejemplos:
<ul><li>np.add(vector,4) # suma 4</li>
<li>np.substract(vector,2) # resta 2</li>
<li>np.multiply</li>
<li>np.floor_divide(vector,3) # devuelve la division entera</li>
<li>np.negative(vector)</li>
<li>np.power(vector,2) #potencia</li>
<li>np.mod(vector,2)</li></ul>

In [ ]:
vector = np.array([(8, 9, 10), (11, 12, 13)])
print(vector.min()) #el elemento menor
print(vector.max()) # el elemento mayor
print(vector.sum()) #suma todos los elementos
print(np.sqrt(vector)) #raíz cuadrada
print(np.std(vector)) #desvío standard
print(np.negative(vector))
print(np.power(vector, 3))
print(np.mod(vector,2))


8
13
63
[[2.82842712 3.         3.16227766]
 [3.31662479 3.46410162 3.60555128]]
1.707825127659933
[[ -8  -9 -10]
 [-11 -12 -13]]
[[ 512  729 1000]
 [1331 1728 2197]]
[[0 1 0]
 [1 0 1]]


In [ ]:
a = np.arange(4)   #[0 1 2 3]
b = np.arange(1,5) #[1 2 3 4]

#display(np.sqrt(a))
print(np.sqrt(a))
print(np.log(b))
print()

print(np.greater(a,b)) #es mayor que
print(np.greater(b,a)) #es mayor que
print()
print( a + b)
print()
print( a - b)

[0.         1.         1.41421356 1.73205081]
[0.         0.69314718 1.09861229 1.38629436]

[False False False False]
[ True  True  True  True]

[1 3 5 7]

[-1 -1 -1 -1]


<h3>Método append</h3>
Para agregar filas o columnas

In [ ]:
print("ARRAY ORIGINAL")
mi_array = np.array(([1,4,19,10,5],[3,9,10,8,8]))
print(mi_array)
print(mi_array.shape)


ARRAY ORIGINAL
[[ 1  4 19 10  5]
 [ 3  9 10  8  8]]
(2, 5)


In [ ]:
# MÉTODO APPEND: ARRAY ORIGINAL +  2 FILAS EXTRA
# axis=0 agrega filas
mi_array2 = np.append(mi_array,([0,0,0,0,0],[1,1,1,1,1]), axis = 0)
#               ↑        ↑                                   ↑
#            método  array original                         eje
print("ARRAY ORIGINAL +  2 FILAS EXTRA")
print(mi_array2)

ARRAY ORIGINAL +  2 FILAS EXTRA
[[ 1  4 19 10  5]
 [ 3  9 10  8  8]
 [ 0  0  0  0  0]
 [ 1  1  1  1  1]]


In [ ]:
# MÉTODO APPEND: ARRAY ORIGINAL + 5 COLUMNAS EXTRA
# Uso el mismo código, pero cambio el axis a 1 -> agrega los datos como columnas
mi_array3 = np.append(mi_array,([0,0,0,0,0],[1,1,1,1,1]), axis = 1)
#               ↑        ↑                                   ↑
#            método  array original                         eje
print("ARRAY ORIGINAL + 5 COLUMNAS EXTRA")
print(mi_array3)

ARRAY ORIGINAL + 5 COLUMNAS EXTRA
[[ 1  4 19 10  5  0  0  0  0  0]
 [ 3  9 10  8  8  1  1  1  1  1]]


<h3>Repaso de acceso a los elementos y slicing</h3>
Para obtener fragmentos de nuestros sets de datos.

In [ ]:
a = np.array([[1,0,3],[4,3,5],[6,10,-1]])
print(a)

[[ 1  0  3]
 [ 4  3  5]
 [ 6 10 -1]]


In [ ]:
# Quiero acceder al 10 (recuerdo que las posiciones empiezan a contarse desde 0)

print(a[2,1])

10


In [ ]:
# recordemos que si estamos en un array de una sola dimensión, ponemos únicamente
# el índice que corresponde al elemento que buscamos y listo!
a2 = np.array([25, 36, 10, 85, 56])
print(a2)
print()
# Busco el 85 -> posición 3 (siempre empiezo a contar de 0)
print(a2[3])

[25 36 10 85 56]

85


In [ ]:
# SLICING TOTAL -> Para obtener todos los elementos
a2 = np.array([25, 36, 10, 85, 56])
print(a2[:])


[25 36 10 85 56]


Puedo usar RANGOS de búsqueda, usando el mismo formato <code><mark>inicio:tope:paso</mark></code> de range.
Supongamos que quiero obtener los datos de las celdas:
<ul><li>naranja</li>
<li>turquesa</li>
<li>rojo</li>
<li>verde</li></ul>
<center><img src='/work/img/slicing.png'></center>

In [ ]:
# CREO LA MATRIZ
matriz = np.array([[0,1,2,3,4,5],[10,11,12,13,14,15],[20,21,22,23,24,25],[30,31,32,33,34,35],[40,41,42,43,44,45],[50,51,52,53,54,55]])


In [ ]:
# BUSCO EL RANGO EN NARANJA
print(matriz[0,3:5])

[3 4]


In [ ]:
print(matriz[0,3:5].reshape(1,2))

[[3 4]]


In [ ]:
# BUSCO EL RANGO TURQUESA
print(matriz[4:,4:])

[[44 45]
 [54 55]]


In [ ]:
# BUSCO EL RANGO ROJO
print(matriz[:,2])

[ 2 12 22 32 42 52]


In [ ]:
# Si quiero que se imprima en columna, recuerdo que tengo el método reshape(filas,columnas)
print(matriz[:,2].reshape(6,1))

[[ 2]
 [12]
 [22]
 [32]
 [42]
 [52]]


In [ ]:
# BUSCO EL RANGO VERDE
print(matriz[2:5:2,:5:2])

[[20 22 24]
 [40 42 44]]


<h3>Boolean Masking</h3>
Puedo obtener información sobre el contenido de mi arreglo, como valores repetidos, por encima o debajo de cierto valor, etc.

Podemos hacerlo mediante operadores mediante o ufuncs

In [ ]:
# CREO UNA MATRIZ CON VALORES ALEATORIOS, pero no quiero que cambien los valores cada vez que ejecuto mi código
np.random.seed(0) # cada vez que se ejecuta, me respeta los nros que creó la 1ra vez

aleatorios = np.random.randint(0,100,(10,10)) # matriz de 10x10 con nros enteros aleatorios entre 0 y 99
print(aleatorios)

[[44 47 64 67 67  9 83 21 36 87]
 [70 88 88 12 58 65 39 87 46 88]
 [81 37 25 77 72  9 20 80 69 79]
 [47 64 82 99 88 49 29 19 19 14]
 [39 32 65  9 57 32 31 74 23 35]
 [75 55 28 34  0  0 36 53  5 38]
 [17 79  4 42 58 31  1 65 41 57]
 [35 11 46 82 91  0 14 99 53 12]
 [42 84 75 68  6 68 47  3 76 52]
 [78 15 20 99 58 23 79 13 85 48]]


In [ ]:
# Uso operadores para buscar
print('TRUE donde el nro es < 50')
print(aleatorios < 50)

TRUE donde el nro es < 50
[[ True  True False False False  True False  True  True False]
 [False False False  True False False  True False  True False]
 [False  True  True False False  True  True False False False]
 [ True False False False False  True  True  True  True  True]
 [ True  True False  True False  True  True False  True  True]
 [False False  True  True  True  True  True False  True  True]
 [ True False  True  True False  True  True False  True False]
 [ True  True  True False False  True  True False False  True]
 [ True False False False  True False  True  True False False]
 [False  True  True False False  True False  True False  True]]


In [ ]:
print('TRUE donde el nro es = 44')
print(aleatorios == 44)

TRUE donde el nro es = 44
[[ True False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]]


In [ ]:
# Con Ufuncs
print("\nDónde tengo elementos = 30?")
print(np.equal(aleatorios, 30)) # busco nros=30



Dónde tengo elementos = 30?
[[False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]]


In [ ]:
print("\nDónde tengo elementos < 32?")
print(np.less(aleatorios, 32))




Dónde tengo elementos < 32?
[[False False False False False  True False  True False False]
 [False False False  True False False False False False False]
 [False False  True False False  True  True False False False]
 [False False False False False False  True  True  True  True]
 [False False False  True False False  True False  True False]
 [False False  True False  True  True False False  True False]
 [ True False  True False False  True  True False False False]
 [False  True False False False  True  True False False  True]
 [False False False False  True False False  True False False]
 [False  True  True False False  True False  True False False]]


In [ ]:
# Contando valores especificos en toda la matriz
print("\nCuántos elementos != 0 tengo? (Los cuenta)")
print(np.count_nonzero(aleatorios))

# Contando valores específicos por fila, agregando la opción axis
print("\nCuántos elementos < 50 tengo en cada fila? (Los cuenta)")
print(np.sum(aleatorios < 50, axis = 1))


Cuántos elementos != 0 tengo? (Los cuenta)
97

Cuántos elementos < 50 tengo en cada fila? (Los cuenta)
[5 3 4 6 7 7 6 6 4 5]


<h3>Método copy</h3>
Permite crear copias de arrays.

In [ ]:
mi_array4 = np.array(([1,4,19,10,5],[3,9,10,8,8]))
mi_array5 = np.copy(mi_array4)

# Confirmo que están alojados en diferentes posiciones de memoria -> Son objetos distintos
print(id(mi_array4))
print(id(mi_array5))


139857023564464
139857023562928


In [ ]:
# Pero si hago:
mi_array6 = mi_array4
print(id(mi_array4))
print(id(mi_array6))
# me estoy refiriendo AL MISMO OBJETO. No estoy creando una copia, y cualquier cosa que haga con 
# mi_array6, va a quedar reflejado en mi_array4 => OJO!!!!!!

139857023564464
139857023564464


<h3>Arreglos de Booleanos</h3>
Con dtype puedo cambiar cómo se muestran los valores en pantalla

In [ ]:
booleanos1 = np.array([1,0,1,1,0,1,0,0])
booleanos2 = np.array([1,0,1,1,0,1,0,0], dtype=bool)

print(booleanos1)
print(booleanos2)
# Recordemos que cualquier nro!=0 es un True

[1 0 1 1 0 1 0 0]
[ True False  True  True False  True False False]


In [ ]:
booleanos1 = np.array([1,0,1,1,0,1,0,0])
booleanos3 = np.array([0,0,1,0,1,1,0,1])

# Puedo Operar!
booleanos4 = booleanos1 & booleanos3 # and
booleanos5 = booleanos1 | booleanos3 # or
print('And:',booleanos4)
print('Or :',booleanos5)




And: [0 0 1 0 0 1 0 0]
Or : [1 0 1 1 1 1 0 1]


In [ ]:
# Aplicando ufuncs obtengo los valores True y False
booleanos6 = np.logical_and(booleanos1, booleanos3)
booleanos7 = np.logical_or(booleanos1, booleanos3)
print('And:',booleanos6)
print('Or :',booleanos7)

And: [False False  True False False  True False False]
Or : [ True False  True  True  True  True False  True]


<h3>all() y any()</h3>
Métodos para evaluar todos los valores de un arreglo

In [ ]:
booleanos1 = np.array([1,0,1,1,0,1,0,0])
booleanos8 = np.array([0,0,0,0,0,0,0,0])
booleanos9 = np.array([1,1,1,1,1,1,1,1])

print('Todos los valores del arreglo están en True?')
print(np.all(booleanos1))
print(np.all(booleanos8))
print(np.all(booleanos9))
print()
print('Hay algún True en el arreglo?')
print(np.any(booleanos1))
print(np.any(booleanos8))
print(np.any(booleanos9))

Todos los valores del arreglo están en True?
False
False
True

Hay algún True en el arreglo?
True
False
True


In [ ]:
# Suponemos que tenemos un array de 3000 edades de personas
edades = np.array([12,67,34,5,26,78, 23, 82, 21])

# Quiero saber si hay alguna persona de 80 o mas años
ochentas = (edades >= 80)
print(ochentas)

print('¿Hay alguna persona de 80 o mas años? : ', np.any(ochentas))

[False False False False False False False  True False]
¿Hay alguna persona de 80 o mas años? :  True


<h3>Broadcasting</h3>
NumPy me permite operar entre arreglos de diferente estructura, transformándolos para que tengan el mismo tamaño para que no se generen errores.

Así es el proceso:
<center><img src='/work/img/broadcasting.png'></center>

<h4>Actividades</h4>
1. Crear un vector3 de 1 fila y 6 columnas con los datos 5,10,15,20,25,30
   Crear un vector4 de 5 filas y 1 columna con los datos 100,200,300,400,500
   (Crédito extra para quien use arange + newaxis para crear los vectores)
   Crear el vector5, a partir de vector4 - vector3

2. Usando slicing, obtener de vector5 los siguientes datos y cargarlos en vector6,vector7,vector8:

In [ ]:
'''
a. [[ 285 280 275 ]
    [ 385 380 375 ]]

b. [ 290 280 270 ]

c. [[  75 ]
    [ 275 ]
    [ 475 ]]
'''

'\na. [[ 285 280 275 ]\n    [ 385 380 375 ]]\n\nb. [ 290 280 270 ]\n\nc. [[  75 ]\n    [ 275 ]\n    [ 475 ]]\n'

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=87cb15be-d633-4c75-99f3-f05591296461' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>